### ISSUE TITLE
Loading OpenDrive Maps fails

### ISSUE THREAD

**Issue by JKinold02** [hatem-darweesh/assuremappingtools#10]
Thanks for the hard work and for providing the mapping tools.
I encounter an issue when i want to load an OpenDrive Map. All the streets seem to be loaded in a narrow area and overlap each other (see the second picture (Town01.xodr)). I loaded the map with the shown settings but had the same problem with different settings, too. 
My goal is to export the CARLA Simulator Maps (https://github.com/carla-simulator/opendrive-test-files/tree/master/OpenDrive) into a Autoware compatible format. I have seen in your tutorials that you managed to convert the CARLA maps and I kindly want to ask, if you could upload the converted maps.
![Import_settings](https://user-images.githubusercontent.com/64009477/82353928-61d13700-9a00-11ea-95d1-3be5e6fe0ea0.png)
![Imported](https://user-images.githubusercontent.com/64009477/82353932-64339100-9a00-11ea-872a-b7336228a510.png)

**Comment by hatem-darweesh** [comment]
Hi @JKinold02  thank you for using ASSURE Maps. 
I have seen similar issue, could not fins exactly what was the reason, maybe Linux library conflict. 

The solution was to follow installation guide for assure tools strictly on a fresh Linux. 

The problem is I can't reproduce this error on my machines and vbox for both  (Ubuntu 18.04, 16.04).
